using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Echo.ZLevels;
using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ECHO.ZLevels.UI;

[GenerateTypedNameReferences]
public sealed partial class ElevatorControllerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    private readonly AccessReaderSystem _access;

    public ElevatorControllerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _access = _entMan.System<AccessReaderSystem>();
    }

    public void Populate(List<ElevatorFloorData> data, bool inProgress)
    {
        ContactsList.RemoveAllChildren();

        ContactsList.Visible = data.Count > 0;
        FetchingAvailableFloorsContainer.Visible = data.Count <= 0;

        if (!_player.LocalEntity.HasValue)
            return;

        data.OrderBy(x => x.Priority);

        foreach (var item in data)
        {
            var button = new Button()
            {
                Text = item.Name,
                HorizontalExpand = true,
                Margin = new Thickness(16, 6),
                ToolTip = HasAccess(item) ? null : Loc.GetString("elevator-access-denied-tooltip"),
                Disabled = inProgress || !HasAccess(item)
            };

            ContactsList.AddChild(button);
        }
    }

    private bool HasAccess(ElevatorFloorData data)
    {
        if (!_player.LocalEntity.HasValue)
            return true;

        return data.Access == null || _access.FindAccessTags(_player.LocalEntity.Value).Contains(data.Access.Value);
    }
}
