using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ECHO.Customization.UI;

[GenerateTypedNameReferences]
public sealed partial class CustomizableBarksWindow : DefaultWindow
{
    public event Action? OnApplyPressed;

    public CustomizableBarksWindow()
    {
        RobustXamlLoader.Load(this);

        ApplyButton.OnPressed += _ => OnApplyPressed?.Invoke();
    }

    public void PopulateTab(string barkId, float pitch, float minVar, float maxVar)
    {
        Tab.SetSelectedBark(barkId, pitch, minVar, maxVar);
    }
}
