using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganTabs.RemoveAllChildren();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            // ECHO-Tweak-start: marking picker whitelists
            // var control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group);
            var layers = _markingsModel.LayersWhitelist == null ? organData.Layers : organData.Layers.Intersect(_markingsModel.LayersWhitelist).ToHashSet();
            var control = new OrganMarkingPicker(_markingsModel, organ, layers, organData.Group);
            // ECHO-Tweak-end

            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = i > 1;
    }
}
