using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Client.PDA;
using Content.Client.UserInterface.Controls;
using Content.Shared._ECHO.Computer;
using Content.Shared.CartridgeLoader;
using Microsoft.VisualBasic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._ECHO.Computer.UI;

[GenerateTypedNameReferences]
public sealed partial class ComputerWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly ClientGameTicker _gameTicker;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action? OnCloseItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;
    public event Action<string, string>? OnLoginButtonPressed;
    public event Action? OnLogOutButtonPressed;
    public event Action? TurnOffComputer;

    private ComputerLoginData? _loginData;
    private bool _programOpen;

    public ComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Divider.Visible = false;

        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        CloseProgramButton.OnPressed += _ => OnCloseItemPressed?.Invoke();

        LoginButton.OnPressed += _ => OnLoginButtonPressed?.Invoke(LoginLineEdit.Text, PasswordLineEdit.Text);
        LogOutButton.OnPressed += _ => OnLogOutButtonPressed?.Invoke();
        TurnOffButton.OnPressed += _ => TurnOffComputer?.Invoke();
    }

    public void Login(ComputerLoginData loginData)
    {
        _loginData = loginData;

        UpdateOpenedProgram();
    }

    public void Logout()
    {
        _loginData = null;

        UpdateOpenedProgram();
    }

    public void SetOpenedWindow(Control? fragment, string? title)
    {
        _programOpen = fragment != null;
        ProgramName.SetMarkup(title ?? "");

        if (fragment == null)
            ProgramContainer.RemoveAllChildren();
        else
            ProgramContainer.AddChild(fragment);

        UpdateOpenedProgram();
    }

    public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
    {
        ProgramList.RemoveAllChildren();

        if (programs.Count == 0)
        {
            ProgramList.AddChild(new Label()
            {
                Text = Loc.GetString("comp-pda-io-no-programs-available"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true
            });

            return;
        }

        foreach (var ent in programs)
        {
            AddProgramItem(ent);
        }
    }

    private void AddProgramItem(Entity<CartridgeComponent> cartridge)
    {
        var item = new ComputerProgramItem();

        item.OpenButton.OnPressed += _ => OnProgramItemPressed?.Invoke(cartridge.Owner);

        if (cartridge.Comp.Icon is not null)
        {
            item.Icon.SetFromSpriteSpecifier(cartridge.Comp.Icon);
            item.Icon.DisplayRect.TextureScale = new(3);
        }

        switch (cartridge.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                item.InstallButton.Visible = true;
                item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(cartridge.Owner);
                break;
            case InstallationStatus.Installed:
                item.InstallButton.Visible = true;
                item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(cartridge.Owner);
                break;
        }

        item.ProgramName.SetMarkup(Loc.GetString(cartridge.Comp.ProgramName));
        ProgramList.AddChild(item);
    }

    private void UpdateOpenedProgram()
    {
        LogOutButton.Disabled = _loginData == null;

        if (_loginData == null)
        {
            ProgramContainerRoot.Visible = false;
            ProgramRoot.Visible = false;
            UserContainerRoot.Visible = true;
        }
        else if (_programOpen)
        {
            ProgramContainerRoot.Visible = false;
            ProgramRoot.Visible = true;
            UserContainerRoot.Visible = false;
        }
        else
        {
            ProgramContainerRoot.Visible = true;
            ProgramRoot.Visible = false;
            UserContainerRoot.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var curRoundTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        var time = new DateTime(PCSystem.CurrentYear, DateTime.Now.Month, DateTime.Now.Day, 12, 0, 0).AddMinutes(curRoundTime.TotalMinutes);
        TimeLabel.SetMessage(time.ToString("hh\\:mm"));
        DateLabel.SetMarkup(time.ToString("dd.MM.yyyy"));
    }
}
